[module]

[module.hugoVersion]
extended = true
min = "0.78.0"

[[module.imports]]
# see https://github.com/iamkun/dayjs for details
path = "github.com/iamkun/dayjs"
disabled = false

[[module.imports.mounts]]
source = "build"
target = "assets/libs/dayjs"
