[module]

[module.hugoVersion]
extended = true
min = "0.70.0"

[[module.imports]]
path = "github.com/popperjs/popper-core"
disable = false

[[module.imports.mounts]]
source = "src"
target = "assets/popper.js"
