name = "DNB Hugo Libs / Popper.js"
license = "MIT"
licenselink = "https://github.com/dnb-hugo/libraries/blob/master/LICENSE"
description = "Popper.js for Hugo"
homepage = "https://github.com/dnb-hugo/libraries"
tags = ["netlify", "hugo", "hugo-theme-component"]
features = []
min_version = "0.70.0"

[author]
  name = "Patrick Kollitsch"
  homepage = "https://github.com/dnb-hugo/libraries/"
